### ISSUE TITLE
发送不了消息

### ISSUE THREAD

**Issue by zzj2039** [cnlimiter/onebot-mirai#10]
`2024-01-22 11:27:48 V/Bot. -> sudo tps
2024-01-22 11:27:49 I/onebot-mirai: Bot:  正向Websocket服务端 收到请求
2024-01-22 11:27:49 E/onebot-mirai: java.lang.IllegalStateException: Not a JSON Array: "命令已提交"
java.lang.IllegalStateException: Not a JSON Array: "命令已提交"
        at OneBot-Mirai-0.2.2.mirai2.jar[private]//com.google.gson.JsonElement.getAsJsonArray(JsonElement.java:117)
        at OneBot-Mirai-0.2.2.mirai2.jar//cn.evole.onebot.mirai.core.ApiMap.sendGroupMessage(ApiMap.java:319)
        at OneBot-Mirai-0.2.2.mirai2.jar//cn.evole.onebot.mirai.core.ApiMap.callMiraiApi(ApiMap.java:83)
        at OneBot-Mirai-0.2.2.mirai2.jar//cn.evole.onebot.mirai.util.ActionUtils.handleWebSocketActions(ActionUtils.java:25)
        at OneBot-Mirai-0.2.2.mirai2.jar//cn.evole.onebot.mirai.web.websocket.OneBotWSServer.onMessage(OneBotWSServer.java:58)
        at OneBot-Mirai-0.2.2.mirai2.jar//org.java_websocket.server.WebSocketServer.onWebsocketMessage(WebSocketServer.java:712)
        at OneBot-Mirai-0.2.2.mirai2.jar//org.java_websocket.drafts.Draft_6455.processFrameText(Draft_6455.java:986)
        at OneBot-Mirai-0.2.2.mirai2.jar//org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:910)
        at OneBot-Mirai-0.2.2.mirai2.jar//org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:401)
        at OneBot-Mirai-0.2.2.mirai2.jar//org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:233)
        at OneBot-Mirai 0.2.2.mirai2.jar//org.java_websocket.server.WebSocketServer$WebSocketWorker.doDecode(WebSocketServer.java:1114)
        at OneBot-Mirai-0.2.2.mirai2.jar//org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:1086)`

**Comment by cnlimiter** [comment]
消息链目前未完全支持，暂时只能用cq码格式

**Comment by cnlimiter** [comment]
还有提交issue记得把关键信息打码，我看到你qq号和群号了

**Comment by cnlimiter** [comment]
已修复
