### ISSUE TITLE
miria报错

### ISSUE THREAD

**Issue by bowen99** [cnlimiter/onebot-mirai#11]
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(status='failed', retcode=103, echo='4')
2024-01-25 16:29:56 E/OneBot_Mirai: java.lang.NullPointerException: Parameter specified as non-null is null: method net.mamoe.mirai.message.data.MessageSource$Key.recall, parameter <this>
java.lang.NullPointerException: Parameter specified as non-null is null: method net.mamoe.mirai.message.data.MessageSource$Key.recall, parameter <this>
        at net.mamoe.mirai.message.data.MessageSource$Key.recall(MessageSource.kt)
        at net.mamoe.mirai.message.data.MessageSource.recall(MessageSource.kt)
        at OneBot-Mirai-0.2.0.mirai2.jar//cn.evole.onebot.mirai.core.ApiMap.deleteMessage(ApiMap.java:363)
        at OneBot-Mirai-0.2.0.mirai2.jar//cn.evole.onebot.mirai.core.ApiMap.callMiraiApi(ApiMap.java:89)
        at OneBot-Mirai-0.2.0.mirai2.jar//cn.evole.onebot.mirai.util.ActionUtils.handleWebSocketActions(ActionUtils.java:25)
        at OneBot-Mirai-0.2.0.mirai2.jar//cn.evole.onebot.mirai.web.websocket.OneBotWSClient.onMessage(OneBotWSClient.java:83)
        at OneBot-Mirai-0.2.0.mirai2.jar//org.java_websocket.client.WebSocketClient.onWebsocketMessage(WebSocketClient.java:636)
        at OneBot-Mirai-0.2.0.mirai2.jar//org.java_websocket.drafts.Draft_6455.processFrameText(Draft_6455.java:986)
        at OneBot-Mirai-0.2.0.mirai2.jar//org.java_websocket.drafts.Draft_6455.processFrame(Draft_6455.java:910)
        at OneBot-Mirai-0.2.0.mirai2.jar//org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:401)
        at OneBot-Mirai-0.2.0.mirai2.jar//org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:233)
        at OneBot-Mirai-0.2.0.mirai2.jar//org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:516)
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by cnlimiter** [comment]
已修复
