### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by zzj2039** [cnlimiter/onebot-mirai#9]
每隔一段时间就会报错
`2024-01-22 12:10:31 W/stderr: java.io.FileNotFoundException: D:\新建文件夹 (2)\data\cn.evole.mirai.onebot\db\db.obm_ (系统找不到指定的路径。)
2024-01-22 12:10:31 W/stderr:   at java.base/java.io.FileOutputStream.open0(Native Method)
2024-01-22 12:10:31 W/stderr:   at java.base/java.io.FileOutputStream.open(Unknown Source)
2024-01-22 12:10:31 W/stderr:   at java.base/java.io.FileOutputStream.<init>(Unknown Source)
2024-01-22 12:10:31 W/stderr:   at java.base/java.io.FileOutputStream.<init>(Unknown Source)
2024-01-22 12:10:31 W/stderr:   at OneBot-Mirai-0.2.2.mirai2.jar//cn.evole.onebot.mirai.database.internal.MapSerl.toFile(MapSerl.java:30)
2024-01-22 12:10:31 W/stderr:   at OneBot-Mirai-0.2.2.mirai2.jar//cn.evole.onebot.mirai.database.NanoDb.save(NanoDb.java:125)
2024-01-22 12:10:31 W/stderr:   at OneBot-Mirai-0.2.2.mirai2.jar//cn.evole.onebot.mirai.database.NanoDb.scheduleSave(NanoDb.java:115)
2024-01-22 12:10:31 W/stderr:   at OneBot-Mirai-0.2.2.mirai2.jar//cn.evole.onebot.mirai.database.NanoDb.set(NanoDb.java:72)
2024-01-22 12:10:31 W/stderr:   at OneBot-Mirai-0.2.2.mirai2.jar//cn.evole.onebot.mirai.util.DBUtils.saveMessageToDB(DBUtils.java:52)
2024-01-22 12:10:31 W/stderr:   at OneBot-Mirai-0.2.2.mirai2.jar//cn.evole.onebot.mirai.OneBotMirai.lambda$onEnable$5(OneBotMirai.java:118)
2024-01-22 12:10:31 W/stderr:   at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:605)
2024-01-22 12:10:31 W/stderr:   at net.mamoe.mirai.event.EventChannel$subscribeAlways$2$1.invoke(EventChannel.kt:605)
2024-01-22 12:10:31 W/stderr:   at kotlinx.coroutines.InterruptibleKt.runInterruptibleInExpectedContext(Interruptible.kt:51)
2024-01-22 12:10:31 W/stderr:   at kotlinx.coroutines.InterruptibleKt.access$runInterruptibleInExpectedContext(Interruptible.kt:1)
2024-01-22 12:10:31 W/stderr:   at kotlinx.coroutines.InterruptibleKt$runInterruptible$2.invokeSuspend(Interruptible.kt:43)
2024-01-22 12:10:31 W/stderr:   at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-01-22 12:10:31 W/stderr:   at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2024-01-22 12:10:31 W/stderr:   at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
2024-01-22 12:10:31 W/stderr:   at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
2024-01-22 12:10:31 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
2024-01-22 12:10:31 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2024-01-22 12:10:31 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
2024-01-22 12:10:31 W/stderr:   at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)`

**Comment by cnlimiter** [comment]
删除该文件D:\新建文件夹 (2)\data\cn.evole.mirai.onebot\db\db.obm_即可
